version: "2"

services:
  db:
    image: mongo:3.3
    container_name: hotel-api-db-mongo

  api:
    build: ./docker/.
    container_name: hotel-api
    entrypoint: /usr/src/app/docker/wait-for-it.sh db:27017 -t 60 -s -- /usr/src/app/docker/run.sh
    depends_on:
     - db
    volumes:
     - .:/usr/src/app/
    ports:
     - "3000:3000"
